### ISSUE TITLE
No asynchronous cache hydration

### ISSUE THREAD

**Issue by LudoTheHUN** [gerritjvv/fun-utils#1]
Hello.

I've noticed that the cache is not hydrated in the background when using `:refresh-after-write`

Here's an example that demonstrated this:

```
(defn wait-and-print [[s ms]]
   (println "starting " s " at " (java.util.Date.))
   (Thread/sleep ms)
   (println "finished " s " at " (java.util.Date.) " waited " ms "ms")
   [s ms (java.util.Date.)])

(defn wait-and-print-cache []
  (cache/create-loading-cache wait-and-print :concurrency-level 4 :refresh-after-write 5000))

(def wait-and-print-cache-memo (memoize wait-and-print-cache))

;;call this continuously, we should never wait after the first cache hydration.  
(time ((wait-and-print-cache-memo)  ["foo1" 1000]))
```

This https://code.google.com/p/guava-libraries/wiki/CachesExplained#Refresh states that
"If CacheLoader.reload is implemented to be asynchronous, then the query will not be slowed down by the refresh."

In turn this means bringing in a ListenableFuture ...

It would be nice to add asych updates as an option.

**Comment by gerritjvv** [comment]
nice, I'm having a look at the PR, 
I'm not a great fan of using future because I've found that under pressure or if the reload function takes a long time to return you might fill the JVM with threads given that it uses Agent. soloExecutor

I'll make the comments I think will make this more flexible

**Comment by gerritjvv** [comment]
mm.. I'll merge in the PR and then think about how to add the possibility of passing in a custom ExecutorService if wanted. 

Thanks!

**Comment by gerritjvv** [comment]
great!, I've added the changes so that its possible to add you're own ExecutorService if required e.g for db background loading etc. and released as fun-utils-0.5.10

**Comment by LudoTheHUN** [comment]
Thank you!

Just a thought: as it is now is good enough for my use case, but I'm naturally weary of dynamic vars. One could pass the Agent/soloExecutor via the args of `create-loading-cache`, with a default still being set to Agent/soloExecutor if none provided. This would let the user use different executors per cache, or share them between specific caches. As is, they are locked into just the one in the dynamic var for all their caches.
I don't have a mental model of what would happen if the var was to be changed while something was executing on that executor... would it be garbage collected? while it is running some work?

**Comment by LudoTheHUN** [comment]
Also, when I checked it out earlier, `lein test` failed to run, was that expected?
You might want to bump the version in the readme.md

**Comment by gerritjvv** [comment]
this project used lein midje but it still fails with the agent-tests I'll make a fix for it. 

The dynamic variable is used so that on cache creation its value is fixed using a let binding 

``` clojure
(let [^ExecutorService exec *executor*]
    (proxy [CacheLoader] []
      (load [k] (f k))
      (reload [k oldvalue]
        (let [fut (SettableFuture/create)]
          (submit exec (.set fut (f k)))
          fut))))
```

this means you can set the executor per cache created when calling `create-loading-cache`

I'm going to do a few things, fix the tests, add an example of how to set the executor, then add the project to travis to compile so all tests are tracked for future use.

**Comment by gerritjvv** [comment]
ok, add travis and fixed the tests.

also the version is automatically updated in the readme using the embedded svg from clojars.

The main reason for using a dynamic var here is the function signature uses varargs that are passed to the loading function, so its not possible to add an optional exec option without breaking the function signature and therefore breaking code that relies on it. I could add a different function name to it maybe, but for the moment binding seems to work as expected, i.e on cache creation the binding value is captured and that value is static for the life of the cache.

**Comment by LudoTheHUN** [comment]
Thanks. That all makes sense.
I was able to run `lein test` and `lein midje` with no issues.
LGTM.

**Comment by gerritjvv** [comment]
great!, thanks.
